services:

  postgresql:
    image: "postgres:10.0"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: C:/roller/docker/postgresql-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rollerdb
      - POSTGRES_USER=scott
      - POSTGRES_PASSWORD=tiger

  roller:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: C:/roller/docker/roller-data
        target: /app/data
